[workspace]
resolver = "2"

members = [
    "servify", "servify_macro",
]

[workspace.package]
version = "0.1.0"
authors = ["AsPulse <contact@aspulse.dev>"]
license = "MIT/Apache-2.0"
edition = "2021"
