[workspace]
resolver = "2"

members = [
    "servify", "servify_macro",
]

[workspace.package]
authors = ["AsPulse <contact@aspulse.dev>"]
license = "MIT/Apache-2.0"
edition = "2021"
repository = "https://github.com/pulsuite/servify"
