[package]
name = "servify_build"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """
Build scripts for use with Servify
"""

[lib]
