[package]
name = "servify_tests"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """
Tests for servify_build
"""

[lib]
