name: build-and-test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
        workspace: [servify, servify_macro]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ matrix.workspace }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --package ${{ matrix.workspace }}
      - name: Run tests
        run: cargo test --package ${{ matrix.workspace }}
